FROM ubuntu:14.10
MAINTAINER notyycn <notyycn@gmail.com>
RUN sudo apt-get update
#RUN sudo mkdir /dev/fuse
#RUN sudo apt-get -y install libfuse2
#RUN sudo apt-get -y install fuse
#RUN sudo apt-get -y install colord
RUN sudo apt-get install -y openjdk-8-jre-headless
