FROM ubuntu:14.10
MAINTAINER notyycn <notyycn@gmail.com>
RUN sudo apt-get update
RUN sudo mkdir /dev/fuse
RUN sudo apt-get install fuse
RUN sudo apt-get install colord
RUN sudo apt-get -y install openjdk-8-jdk
